version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             sleep 2 &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             gunicorn farmbid.wsgi:application -b 0.0.0.0:8000 --error-logfile gunicorn.error"
    volumes:
      - .:/django_app
      - ./container_log/:/var/log/
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./container_log/:/var/log/
      - ./static/:/django_app/static/
    depends_on:
      - web
volumes:
  django_app:
  nginx_conf:
  static:
  container_log: