# Generated by Django 2.1.7 on 2019-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rated_to',
        ),
        migrations.AlterField(
            model_name='bid',
            name='current_highest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_sold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
