# Generated by Django 2.1.7 on 2019-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190304_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='task_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
