# Generated by Django 2.1.7 on 2019-03-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190305_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='n_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
